// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5HziYqObQovSNWsTwkPjKWWFpkpXjeyg',
    appId: '1:223829314435:web:8d88e0fd4331bdf82dc4b6',
    messagingSenderId: '223829314435',
    projectId: 'test-app-2b5fd',
    authDomain: 'test-app-2b5fd.firebaseapp.com',
    storageBucket: 'test-app-2b5fd.firebasestorage.app',
    measurementId: 'G-8JX378CB6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxB-IMKAvxUmi5MbgXFQol5Ds6HWrcqGA',
    appId: '1:223829314435:android:8528920cb7e6ce5a2dc4b6',
    messagingSenderId: '223829314435',
    projectId: 'test-app-2b5fd',
    storageBucket: 'test-app-2b5fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLMnXDcHEjQ7_3cEN_Ru7upFVYxRalAXI',
    appId: '1:223829314435:ios:a9cca4edc13546bc2dc4b6',
    messagingSenderId: '223829314435',
    projectId: 'test-app-2b5fd',
    storageBucket: 'test-app-2b5fd.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLMnXDcHEjQ7_3cEN_Ru7upFVYxRalAXI',
    appId: '1:223829314435:ios:a9cca4edc13546bc2dc4b6',
    messagingSenderId: '223829314435',
    projectId: 'test-app-2b5fd',
    storageBucket: 'test-app-2b5fd.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5HziYqObQovSNWsTwkPjKWWFpkpXjeyg',
    appId: '1:223829314435:web:e15fe1e702b26b082dc4b6',
    messagingSenderId: '223829314435',
    projectId: 'test-app-2b5fd',
    authDomain: 'test-app-2b5fd.firebaseapp.com',
    storageBucket: 'test-app-2b5fd.firebasestorage.app',
    measurementId: 'G-DHSVFEYN10',
  );
}
